# coding: utf-8

# flake8: noqa

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: nils.hoffmann@isas.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.validate_api import ValidateApi
from swagger_client.api.validate_plain_api import ValidatePlainApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.column_parameter_mapping import ColumnParameterMapping
from swagger_client.models.comment import Comment
from swagger_client.models.error import Error
from swagger_client.models.indexed_element import IndexedElement
from swagger_client.models.metadata import Metadata
from swagger_client.models.mz_tab import MzTab
from swagger_client.models.opt_column_mapping import OptColumnMapping
from swagger_client.models.publication_item import PublicationItem
from swagger_client.models.small_molecule_evidence import SmallMoleculeEvidence
from swagger_client.models.small_molecule_feature import SmallMoleculeFeature
from swagger_client.models.small_molecule_summary import SmallMoleculeSummary
from swagger_client.models.spectra_ref import SpectraRef
from swagger_client.models.string_list import StringList
from swagger_client.models.validation_message import ValidationMessage
from swagger_client.models.assay import Assay
from swagger_client.models.cv import CV
from swagger_client.models.contact import Contact
from swagger_client.models.database import Database
from swagger_client.models.instrument import Instrument
from swagger_client.models.ms_run import MsRun
from swagger_client.models.parameter import Parameter
from swagger_client.models.publication import Publication
from swagger_client.models.sample import Sample
from swagger_client.models.sample_processing import SampleProcessing
from swagger_client.models.software import Software
from swagger_client.models.study_variable import StudyVariable
from swagger_client.models.uri import Uri
