# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mztabm_client.models.spectra_ref import SpectraRef

class TestSpectraRef(unittest.TestCase):
    """SpectraRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpectraRef:
        """Test SpectraRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpectraRef`
        """
        model = SpectraRef()
        if include_optional:
            return SpectraRef(
                ms_run = openapi_client.models.ms_run.MsRun(
                    id = 1, 
                    name = '', 
                    location = '', 
                    instrument_ref = openapi_client.models.instrument.Instrument(
                        id = 1, 
                        name = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '', 
                            cv_accession = '', 
                            name = '', 
                            value = '', ), 
                        source = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '', 
                            cv_accession = '', 
                            name = '', 
                            value = '', ), 
                        analyzer = [
                            
                            ], 
                        detector = , ), 
                    format = , 
                    id_format = , 
                    fragmentation_method = [
                        
                        ], 
                    scan_polarity = [
                        
                        ], 
                    hash = '', 
                    hash_method = , ),
                reference = ''
            )
        else:
            return SpectraRef(
                ms_run = openapi_client.models.ms_run.MsRun(
                    id = 1, 
                    name = '', 
                    location = '', 
                    instrument_ref = openapi_client.models.instrument.Instrument(
                        id = 1, 
                        name = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '', 
                            cv_accession = '', 
                            name = '', 
                            value = '', ), 
                        source = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '', 
                            cv_accession = '', 
                            name = '', 
                            value = '', ), 
                        analyzer = [
                            
                            ], 
                        detector = , ), 
                    format = , 
                    id_format = , 
                    fragmentation_method = [
                        
                        ], 
                    scan_polarity = [
                        
                        ], 
                    hash = '', 
                    hash_method = , ),
                reference = '',
        )
        """

    def testSpectraRef(self):
        """Test SpectraRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
