# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mztabm_client.api.validate_api import ValidateApi


class TestValidateApi(unittest.TestCase):
    """ValidateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidateApi()

    def tearDown(self) -> None:
        pass

    def test_validate_mz_tab_file(self) -> None:
        """Test case for validate_mz_tab_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
