# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mztabm_client.models.small_molecule_feature import SmallMoleculeFeature

class TestSmallMoleculeFeature(unittest.TestCase):
    """SmallMoleculeFeature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmallMoleculeFeature:
        """Test SmallMoleculeFeature
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmallMoleculeFeature`
        """
        model = SmallMoleculeFeature()
        if include_optional:
            return SmallMoleculeFeature(
                prefix = 'SMF',
                header_prefix = 'SFH',
                smf_id = 56,
                sme_id_refs = [
                    56
                    ],
                sme_id_ref_ambiguity_code = 56,
                adduct_ion = '[4807288800152802179809M+RYnua_cdyyvLY8IzLpul91GcWjTkp6JIZDm7w0v1d_fVofvLFSjsmJnZAs0FmNI7kw9gsnYv3_8jSQL653YHp9_]8648829166332287705219191166478378563875565986836152+',
                isotopomer = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '', 
                    cv_accession = '', 
                    name = '', 
                    value = '', ),
                exp_mass_to_charge = 1.337,
                charge = 56,
                retention_time_in_seconds = 1.337,
                retention_time_in_seconds_start = 1.337,
                retention_time_in_seconds_end = 1.337,
                abundance_assay = [
                    1.337
                    ],
                opt = [
                    openapi_client.models.opt_column_mapping.OptColumnMapping(
                        identifier = '', 
                        param = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '', 
                            cv_accession = '', 
                            name = '', 
                            value = '', ), 
                        value = '', )
                    ],
                comment = [
                    openapi_client.models.comment.Comment(
                        prefix = 'COM', 
                        msg = '', 
                        line_number = 56, )
                    ]
            )
        else:
            return SmallMoleculeFeature(
                smf_id = 56,
                exp_mass_to_charge = 1.337,
                charge = 56,
        )
        """

    def testSmallMoleculeFeature(self):
        """Test SmallMoleculeFeature"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
