# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@isas.de
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.metadata import Metadata  # noqa: E501
from openapi_client.rest import ApiException

class TestMetadata(unittest.TestCase):
    """Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Metadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.metadata.Metadata()  # noqa: E501
        if include_optional :
            return Metadata(
                prefix = 'MTD', 
                mz_tab_version = 'a', 
                mz_tab_id = 'MTD mzTab-ID MTBLS214', 
                title = 'MTD title My first test experiment', 
                description = 'MTD description An experiment investigating the effects of Il-6.', 
                contact = [
                    openapi_client.models.contact.Contact(
                        id = 1, 
                        name = '0', 
                        affiliation = '0', 
                        email = 'a', )
                    ], 
                publication = [
                    openapi_client.models.publication.Publication(
                        id = 1, 
                        publication_items = [
                            openapi_client.models.publication_item.PublicationItem(
                                type = 'doi', 
                                accession = '0', )
                            ], )
                    ], 
                uri = [
                    openapi_client.models.uri.Uri(
                        id = 1, 
                        value = '0', )
                    ], 
                external_study_uri = [
                    openapi_client.models.uri.Uri(
                        id = 1, 
                        value = '0', )
                    ], 
                instrument = [
                    openapi_client.models.instrument.Instrument(
                        id = 1, 
                        name = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        source = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        analyzer = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        detector = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), )
                    ], 
                quantification_method = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ), 
                sample = [
                    openapi_client.models.sample.Sample(
                        id = 1, 
                        name = '0', 
                        custom = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        species = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        tissue = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        cell_type = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        disease = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        description = '0', )
                    ], 
                sample_processing = [
                    openapi_client.models.sample_processing.SampleProcessing(
                        id = 1, 
                        sample_processing = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], )
                    ], 
                software = [
                    openapi_client.models.software.Software(
                        id = 1, 
                        parameter = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        setting = [
                            '0'
                            ], )
                    ], 
                derivatization_agent = [
                    openapi_client.models.parameter.Parameter(
                        id = 1, 
                        cv_label = '0', 
                        cv_accession = '0', 
                        name = '0', 
                        value = '0', )
                    ], 
                ms_run = [
                    openapi_client.models.ms_run.MsRun(
                        id = 1, 
                        name = '0', 
                        location = '0', 
                        instrument_ref = openapi_client.models.instrument.Instrument(
                            id = 1, 
                            name = openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', ), 
                            source = openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', ), 
                            analyzer = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            detector = openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', ), ), 
                        format = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        id_format = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        fragmentation_method = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        scan_polarity = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        hash = '0', 
                        hash_method = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), )
                    ], 
                assay = [
                    openapi_client.models.assay.Assay(
                        id = 1, 
                        name = '0', 
                        custom = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        external_uri = '0', 
                        sample_ref = openapi_client.models.sample.Sample(
                            id = 1, 
                            name = '0', 
                            species = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            tissue = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            cell_type = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            disease = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            description = '0', ), 
                        ms_run_ref = [
                            openapi_client.models.ms_run.MsRun(
                                id = 1, 
                                name = '0', 
                                location = '0', 
                                instrument_ref = openapi_client.models.instrument.Instrument(
                                    id = 1, 
                                    name = openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', ), 
                                    source = openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', ), 
                                    analyzer = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    detector = openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', ), ), 
                                format = openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', ), 
                                id_format = openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', ), 
                                fragmentation_method = [
                                    openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', )
                                    ], 
                                scan_polarity = [
                                    openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', )
                                    ], 
                                hash = '0', 
                                hash_method = openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', ), )
                            ], )
                    ], 
                study_variable = [
                    openapi_client.models.study_variable.StudyVariable(
                        id = 1, 
                        name = '0', 
                        assay_refs = [
                            openapi_client.models.assay.Assay(
                                id = 1, 
                                name = '0', 
                                custom = [
                                    openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', )
                                    ], 
                                external_uri = '0', 
                                sample_ref = openapi_client.models.sample.Sample(
                                    id = 1, 
                                    name = '0', 
                                    species = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    tissue = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    cell_type = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    disease = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    description = '0', ), 
                                ms_run_ref = [
                                    openapi_client.models.ms_run.MsRun(
                                        id = 1, 
                                        name = '0', 
                                        location = '0', 
                                        instrument_ref = openapi_client.models.instrument.Instrument(
                                            id = 1, 
                                            name = openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', ), 
                                            source = openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', ), 
                                            analyzer = [
                                                openapi_client.models.parameter.Parameter(
                                                    id = 1, 
                                                    cv_label = '0', 
                                                    cv_accession = '0', 
                                                    name = '0', 
                                                    value = '0', )
                                                ], 
                                            detector = openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', ), ), 
                                        format = openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', ), 
                                        id_format = openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', ), 
                                        fragmentation_method = [
                                            openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', )
                                            ], 
                                        scan_polarity = [
                                            openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', )
                                            ], 
                                        hash = '0', 
                                        hash_method = openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', ), )
                                    ], )
                            ], 
                        average_function = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        variation_function = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        description = '0', 
                        factors = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], )
                    ], 
                custom = [
                    openapi_client.models.parameter.Parameter(
                        id = 1, 
                        cv_label = '0', 
                        cv_accession = '0', 
                        name = '0', 
                        value = '0', )
                    ], 
                cv = [
                    openapi_client.models.cv.CV(
                        id = 1, 
                        label = '0', 
                        full_name = '0', 
                        version = '0', 
                        uri = '0', )
                    ], 
                small_molecule_quantification_unit = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ), 
                small_molecule_feature_quantification_unit = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ), 
                small_molecule_identification_reliability = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ), 
                database = [
                    openapi_client.models.database.Database(
                        id = 1, 
                        param = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        prefix = '0', 
                        version = '0', 
                        uri = '0', )
                    ], 
                id_confidence_measure = [
                    openapi_client.models.parameter.Parameter(
                        id = 1, 
                        cv_label = '0', 
                        cv_accession = '0', 
                        name = '0', 
                        value = '0', )
                    ], 
                colunit_small_molecule = [
                    openapi_client.models.column_parameter_mapping.ColumnParameterMapping(
                        column_name = '0', 
                        param = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), )
                    ], 
                colunit_small_molecule_feature = [
                    openapi_client.models.column_parameter_mapping.ColumnParameterMapping(
                        column_name = '0', 
                        param = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), )
                    ], 
                colunit_small_molecule_evidence = [
                    openapi_client.models.column_parameter_mapping.ColumnParameterMapping(
                        column_name = '0', 
                        param = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), )
                    ]
            )
        else :
            return Metadata(
                prefix = 'MTD',
                mz_tab_version = 'a',
                mz_tab_id = 'MTD mzTab-ID MTBLS214',
                quantification_method = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ),
                software = [
                    openapi_client.models.software.Software(
                        id = 1, 
                        parameter = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        setting = [
                            '0'
                            ], )
                    ],
                ms_run = [
                    openapi_client.models.ms_run.MsRun(
                        id = 1, 
                        name = '0', 
                        location = '0', 
                        instrument_ref = openapi_client.models.instrument.Instrument(
                            id = 1, 
                            name = openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', ), 
                            source = openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', ), 
                            analyzer = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            detector = openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', ), ), 
                        format = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        id_format = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        fragmentation_method = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        scan_polarity = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        hash = '0', 
                        hash_method = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), )
                    ],
                assay = [
                    openapi_client.models.assay.Assay(
                        id = 1, 
                        name = '0', 
                        custom = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], 
                        external_uri = '0', 
                        sample_ref = openapi_client.models.sample.Sample(
                            id = 1, 
                            name = '0', 
                            species = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            tissue = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            cell_type = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            disease = [
                                openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', )
                                ], 
                            description = '0', ), 
                        ms_run_ref = [
                            openapi_client.models.ms_run.MsRun(
                                id = 1, 
                                name = '0', 
                                location = '0', 
                                instrument_ref = openapi_client.models.instrument.Instrument(
                                    id = 1, 
                                    name = openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', ), 
                                    source = openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', ), 
                                    analyzer = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    detector = openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', ), ), 
                                format = openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', ), 
                                id_format = openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', ), 
                                fragmentation_method = [
                                    openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', )
                                    ], 
                                scan_polarity = [
                                    openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', )
                                    ], 
                                hash = '0', 
                                hash_method = openapi_client.models.parameter.Parameter(
                                    id = 1, 
                                    cv_label = '0', 
                                    cv_accession = '0', 
                                    name = '0', 
                                    value = '0', ), )
                            ], )
                    ],
                study_variable = [
                    openapi_client.models.study_variable.StudyVariable(
                        id = 1, 
                        name = '0', 
                        assay_refs = [
                            openapi_client.models.assay.Assay(
                                id = 1, 
                                name = '0', 
                                custom = [
                                    openapi_client.models.parameter.Parameter(
                                        id = 1, 
                                        cv_label = '0', 
                                        cv_accession = '0', 
                                        name = '0', 
                                        value = '0', )
                                    ], 
                                external_uri = '0', 
                                sample_ref = openapi_client.models.sample.Sample(
                                    id = 1, 
                                    name = '0', 
                                    species = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    tissue = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    cell_type = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    disease = [
                                        openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', )
                                        ], 
                                    description = '0', ), 
                                ms_run_ref = [
                                    openapi_client.models.ms_run.MsRun(
                                        id = 1, 
                                        name = '0', 
                                        location = '0', 
                                        instrument_ref = openapi_client.models.instrument.Instrument(
                                            id = 1, 
                                            name = openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', ), 
                                            source = openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', ), 
                                            analyzer = [
                                                openapi_client.models.parameter.Parameter(
                                                    id = 1, 
                                                    cv_label = '0', 
                                                    cv_accession = '0', 
                                                    name = '0', 
                                                    value = '0', )
                                                ], 
                                            detector = openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', ), ), 
                                        format = openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', ), 
                                        id_format = openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', ), 
                                        fragmentation_method = [
                                            openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', )
                                            ], 
                                        scan_polarity = [
                                            openapi_client.models.parameter.Parameter(
                                                id = 1, 
                                                cv_label = '0', 
                                                cv_accession = '0', 
                                                name = '0', 
                                                value = '0', )
                                            ], 
                                        hash = '0', 
                                        hash_method = openapi_client.models.parameter.Parameter(
                                            id = 1, 
                                            cv_label = '0', 
                                            cv_accession = '0', 
                                            name = '0', 
                                            value = '0', ), )
                                    ], )
                            ], 
                        average_function = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        variation_function = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        description = '0', 
                        factors = [
                            openapi_client.models.parameter.Parameter(
                                id = 1, 
                                cv_label = '0', 
                                cv_accession = '0', 
                                name = '0', 
                                value = '0', )
                            ], )
                    ],
                cv = [
                    openapi_client.models.cv.CV(
                        id = 1, 
                        label = '0', 
                        full_name = '0', 
                        version = '0', 
                        uri = '0', )
                    ],
                small_molecule_quantification_unit = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ),
                small_molecule_feature_quantification_unit = openapi_client.models.parameter.Parameter(
                    id = 1, 
                    cv_label = '0', 
                    cv_accession = '0', 
                    name = '0', 
                    value = '0', ),
                database = [
                    openapi_client.models.database.Database(
                        id = 1, 
                        param = openapi_client.models.parameter.Parameter(
                            id = 1, 
                            cv_label = '0', 
                            cv_accession = '0', 
                            name = '0', 
                            value = '0', ), 
                        prefix = '0', 
                        version = '0', 
                        uri = '0', )
                    ],
                id_confidence_measure = [
                    openapi_client.models.parameter.Parameter(
                        id = 1, 
                        cv_label = '0', 
                        cv_accession = '0', 
                        name = '0', 
                        value = '0', )
                    ],
        )

    def testMetadata(self):
        """Test Metadata"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
