# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mztabm_client.models.publication_item import PublicationItem

class TestPublicationItem(unittest.TestCase):
    """PublicationItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicationItem:
        """Test PublicationItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicationItem`
        """
        model = PublicationItem()
        if include_optional:
            return PublicationItem(
                type = 'doi',
                accession = ''
            )
        else:
            return PublicationItem(
                type = 'doi',
                accession = '',
        )
        """

    def testPublicationItem(self):
        """Test PublicationItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
