# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mztabm_client.models.cv import CV

class TestCV(unittest.TestCase):
    """CV unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CV:
        """Test CV
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CV`
        """
        model = CV()
        if include_optional:
            return CV(
                id = 1,
                label = '',
                full_name = '',
                version = '',
                uri = ''
            )
        else:
            return CV(
                label = '',
                full_name = '',
                version = '',
                uri = '',
        )
        """

    def testCV(self):
        """Test CV"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
