site_name: pymzTab-m
site_description: Python implementation of the mzTab-M standard in Python.
site_url: https://pymztab-m.readthedocs.io/
repo_url: https://github.com/lifs-tools/pymzTab-m
repo_name: lifs-tools/pymzTab-m
docs_dir: docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            extensions:
              - griffe_pydantic:
                  schema: true
            docstring_style: google
            merge_init_into_class: true
            show_root_heading: true
            show_signature: true
            show_if_no_docstring: true
            members_order: source
          import:
            - https://docs.pydantic.dev/latest/objects.inv
  - autorefs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
