# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: nils.hoffmann@isas.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mztab_m_swagger_client
from mztab_m_swagger_client.models.comment import Comment  # noqa: E501
from mztab_m_swagger_client.rest import ApiException


class TestComment(unittest.TestCase):
    """Comment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComment(self):
        """Test Comment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mztab_m_swagger_client.models.comment.Comment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
