# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from mztabm_client.models.mz_tab import MzTab
from mztabm_client.models.validation_message import ValidationMessage

from mztabm_client.api_client import ApiClient, RequestSerialized
from mztabm_client.api_response import ApiResponse
from mztabm_client.rest import RESTResponseType


class ValidateApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def validate_mz_tab_file(
        self,
        mz_tab: Annotated[MzTab, Field(description="mzTab file that should be validated.")],
        level: Annotated[Optional[StrictStr], Field(description="The level of errors that should be reported, one of ERROR, WARN, INFO.")] = None,
        max_errors: Annotated[Optional[Annotated[int, Field(le=500, strict=True, ge=0)]], Field(description="The maximum number of errors to return.")] = None,
        semantic_validation: Annotated[Optional[StrictBool], Field(description="Whether a semantic validation against the default rule set should be performed.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[ValidationMessage]:
        """validate_mz_tab_file

        Validates an mzTab file in XML or JSON representation and reports syntactic, structural, and semantic errors. 

        :param mz_tab: mzTab file that should be validated. (required)
        :type mz_tab: MzTab
        :param level: The level of errors that should be reported, one of ERROR, WARN, INFO.
        :type level: str
        :param max_errors: The maximum number of errors to return.
        :type max_errors: int
        :param semantic_validation: Whether a semantic validation against the default rule set should be performed.
        :type semantic_validation: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._validate_mz_tab_file_serialize(
            mz_tab=mz_tab,
            level=level,
            max_errors=max_errors,
            semantic_validation=semantic_validation,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ValidationMessage]",
            '415': None,
            '422': "List[ValidationMessage]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def validate_mz_tab_file_with_http_info(
        self,
        mz_tab: Annotated[MzTab, Field(description="mzTab file that should be validated.")],
        level: Annotated[Optional[StrictStr], Field(description="The level of errors that should be reported, one of ERROR, WARN, INFO.")] = None,
        max_errors: Annotated[Optional[Annotated[int, Field(le=500, strict=True, ge=0)]], Field(description="The maximum number of errors to return.")] = None,
        semantic_validation: Annotated[Optional[StrictBool], Field(description="Whether a semantic validation against the default rule set should be performed.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[ValidationMessage]]:
        """validate_mz_tab_file

        Validates an mzTab file in XML or JSON representation and reports syntactic, structural, and semantic errors. 

        :param mz_tab: mzTab file that should be validated. (required)
        :type mz_tab: MzTab
        :param level: The level of errors that should be reported, one of ERROR, WARN, INFO.
        :type level: str
        :param max_errors: The maximum number of errors to return.
        :type max_errors: int
        :param semantic_validation: Whether a semantic validation against the default rule set should be performed.
        :type semantic_validation: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._validate_mz_tab_file_serialize(
            mz_tab=mz_tab,
            level=level,
            max_errors=max_errors,
            semantic_validation=semantic_validation,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ValidationMessage]",
            '415': None,
            '422': "List[ValidationMessage]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def validate_mz_tab_file_without_preload_content(
        self,
        mz_tab: Annotated[MzTab, Field(description="mzTab file that should be validated.")],
        level: Annotated[Optional[StrictStr], Field(description="The level of errors that should be reported, one of ERROR, WARN, INFO.")] = None,
        max_errors: Annotated[Optional[Annotated[int, Field(le=500, strict=True, ge=0)]], Field(description="The maximum number of errors to return.")] = None,
        semantic_validation: Annotated[Optional[StrictBool], Field(description="Whether a semantic validation against the default rule set should be performed.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """validate_mz_tab_file

        Validates an mzTab file in XML or JSON representation and reports syntactic, structural, and semantic errors. 

        :param mz_tab: mzTab file that should be validated. (required)
        :type mz_tab: MzTab
        :param level: The level of errors that should be reported, one of ERROR, WARN, INFO.
        :type level: str
        :param max_errors: The maximum number of errors to return.
        :type max_errors: int
        :param semantic_validation: Whether a semantic validation against the default rule set should be performed.
        :type semantic_validation: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._validate_mz_tab_file_serialize(
            mz_tab=mz_tab,
            level=level,
            max_errors=max_errors,
            semantic_validation=semantic_validation,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ValidationMessage]",
            '415': None,
            '422': "List[ValidationMessage]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _validate_mz_tab_file_serialize(
        self,
        mz_tab,
        level,
        max_errors,
        semantic_validation,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if level is not None:
            
            _query_params.append(('level', level))
            
        if max_errors is not None:
            
            _query_params.append(('maxErrors', max_errors))
            
        if semantic_validation is not None:
            
            _query_params.append(('semanticValidation', semantic_validation))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if mz_tab is not None:
            _body_params = mz_tab


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json', 
                        'application/xml'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/validate',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


