# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: nils.hoffmann@isas.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client import ApiClient
from swagger_client.api.validate_plain_api import ValidatePlainApi  # noqa: E501
from swagger_client.rest import ApiException


class TestValidatePlainApi(unittest.TestCase):
    """ValidatePlainApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.validate_plain_api.ValidatePlainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_validate_plain_mz_tab_file(self):
        """Test case for validate_plain_mz_tab_file

        """
        import os
        # os.chdir(os.path.dirname(__file__))
        print(os.getcwd())
        filePath = 'data/lipidomics-example.mzTab'
        with open(filePath, 'r') as mzTabFile:
            txt = mzTabFile.read()
        
        self.api.validate_plain_mz_tab_file(txt)
        """Test case for validate_mz_tab_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
