# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: nils.hoffmann@isas.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.spectra_ref import SpectraRef  # noqa: E501
from swagger_client.rest import ApiException


class TestSpectraRef(unittest.TestCase):
    """SpectraRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpectraRef(self):
        """Test SpectraRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.spectra_ref.SpectraRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
