# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: nils.hoffmann@isas.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from mztab_m_swagger_client.api_client import ApiClient


class ValidatePlainApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def validate_plain_mz_tab_file(self, mztabfile, **kwargs):  # noqa: E501
        """validate_plain_mz_tab_file  # noqa: E501

        Validates an mzTab file in plain text representation / tab-separated format and reports syntactic, structural, and semantic errors.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.validate_plain_mz_tab_file(mztabfile, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str mztabfile: mzTab file that should be validated. (required)
        :param str level: The level of errors that should be reported, one of ERROR, WARN, INFO.
        :param int max_errors: The maximum number of errors to return.
        :param bool semantic_validation: Whether a semantic validation against the default rule set should be performed.
        :return: list[ValidationMessage]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.validate_plain_mz_tab_file_with_http_info(mztabfile, **kwargs)  # noqa: E501
        else:
            (data) = self.validate_plain_mz_tab_file_with_http_info(mztabfile, **kwargs)  # noqa: E501
            return data

    def validate_plain_mz_tab_file_with_http_info(self, mztabfile, **kwargs):  # noqa: E501
        """validate_plain_mz_tab_file  # noqa: E501

        Validates an mzTab file in plain text representation / tab-separated format and reports syntactic, structural, and semantic errors.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.validate_plain_mz_tab_file_with_http_info(mztabfile, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str mztabfile: mzTab file that should be validated. (required)
        :param str level: The level of errors that should be reported, one of ERROR, WARN, INFO.
        :param int max_errors: The maximum number of errors to return.
        :param bool semantic_validation: Whether a semantic validation against the default rule set should be performed.
        :return: list[ValidationMessage]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mztabfile', 'level', 'max_errors', 'semantic_validation']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method validate_plain_mz_tab_file" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mztabfile' is set
        if ('mztabfile' not in params or
                params['mztabfile'] is None):
            raise ValueError("Missing the required parameter `mztabfile` when calling `validate_plain_mz_tab_file`")  # noqa: E501

        if 'max_errors' in params and params['max_errors'] > 500:  # noqa: E501
            raise ValueError("Invalid value for parameter `max_errors` when calling `validate_plain_mz_tab_file`, must be a value less than or equal to `500`")  # noqa: E501
        if 'max_errors' in params and params['max_errors'] < 0:  # noqa: E501
            raise ValueError("Invalid value for parameter `max_errors` when calling `validate_plain_mz_tab_file`, must be a value greater than or equal to `0`")  # noqa: E501
        collection_formats = {}

        path_params = {}

        query_params = []
        if 'level' in params:
            query_params.append(('level', params['level']))  # noqa: E501
        if 'max_errors' in params:
            query_params.append(('maxErrors', params['max_errors']))  # noqa: E501
        if 'semantic_validation' in params:
            query_params.append(('semanticValidation', params['semantic_validation']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'mztabfile' in params:
            body_params = params['mztabfile']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['text/tab-separated-values', 'text/plain'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/validatePlain', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ValidationMessage]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
