# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mztabm_client.models.instrument import Instrument
from mztabm_client.models.parameter import Parameter
from typing import Optional, Set
from typing_extensions import Self

class MsRun(BaseModel):
    """
    Specification of ms_run.  location: Location of the external data file e.g. raw files on which analysis has been performed. If the actual location of the MS run is unknown, a “null” MUST be used as a place holder value, since the [1-n] cardinality is referenced elsewhere. If pre-fractionation has been performed, then [1-n] ms_runs SHOULD be created per assay.  instrument_ref: If different instruments are used in different runs, instrument_ref can be used to link a specific instrument to a specific run.  format: Parameter specifying the data format of the external MS data file. If ms_run[1-n]-format is present, ms_run[1-n]-id_format SHOULD also be present, following the parameters specified in Table 1.  id_format: Parameter specifying the id format used in the external data file. If ms_run[1-n]-id_format is present, ms_run[1-n]-format SHOULD also be present. fragmentation_method: The type(s) of fragmentation used in a given ms run. scan_polarity: The polarity mode of a given run. Usually only one value SHOULD be given here except for the case of mixed polarity runs. hash: Hash value of the corresponding external MS data file defined in ms_run[1-n]-location. If ms_run[1-n]-hash is present, ms_run[1-n]-hash_method SHOULD also be present. hash_method: A parameter specifying the hash methods used to generate the String in ms_run[1-n]-hash. Specifics of the hash method used MAY follow the definitions of the mzML format. If ms_run[1-n]-hash is present, ms_run[1-n]-hash_method SHOULD also be present. 
    """ # noqa: E501
    id: Annotated[int, Field(strict=True, ge=1)]
    name: Optional[StrictStr] = Field(default=None, description="The msRun's name.")
    location: StrictStr = Field(description="The msRun's location URI.")
    instrument_ref: Optional[Instrument] = None
    format: Optional[Parameter] = None
    id_format: Optional[Parameter] = None
    fragmentation_method: Optional[List[Parameter]] = Field(default=None, description="The fragmentation methods applied during this msRun.")
    scan_polarity: Optional[List[Parameter]] = Field(default=None, description="The scan polarity/polarities used during this msRun.")
    hash: Optional[StrictStr] = Field(default=None, description="The file hash value of this msRun's data file.")
    hash_method: Optional[Parameter] = None
    __properties: ClassVar[List[str]] = ["id", "name", "location", "instrument_ref", "format", "id_format", "fragmentation_method", "scan_polarity", "hash", "hash_method"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MsRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of instrument_ref
        if self.instrument_ref:
            _dict['instrument_ref'] = self.instrument_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of format
        if self.format:
            _dict['format'] = self.format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of id_format
        if self.id_format:
            _dict['id_format'] = self.id_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in fragmentation_method (list)
        _items = []
        if self.fragmentation_method:
            for _item in self.fragmentation_method:
                if _item:
                    _items.append(_item.to_dict())
            _dict['fragmentation_method'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in scan_polarity (list)
        _items = []
        if self.scan_polarity:
            for _item in self.scan_polarity:
                if _item:
                    _items.append(_item.to_dict())
            _dict['scan_polarity'] = _items
        # override the default output from pydantic by calling `to_dict()` of hash_method
        if self.hash_method:
            _dict['hash_method'] = self.hash_method.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MsRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "location": obj.get("location"),
            "instrument_ref": Instrument.from_dict(obj["instrument_ref"]) if obj.get("instrument_ref") is not None else None,
            "format": Parameter.from_dict(obj["format"]) if obj.get("format") is not None else None,
            "id_format": Parameter.from_dict(obj["id_format"]) if obj.get("id_format") is not None else None,
            "fragmentation_method": [Parameter.from_dict(_item) for _item in obj["fragmentation_method"]] if obj.get("fragmentation_method") is not None else None,
            "scan_polarity": [Parameter.from_dict(_item) for _item in obj["scan_polarity"]] if obj.get("scan_polarity") is not None else None,
            "hash": obj.get("hash"),
            "hash_method": Parameter.from_dict(obj["hash_method"]) if obj.get("hash_method") is not None else None
        })
        return _obj


