# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mztabm_client.models.parameter import Parameter
from typing import Optional, Set
from typing_extensions import Self

class Sample(BaseModel):
    """
    Specification of sample. (empty) name: A name for each sample to serve as a list of the samples that MUST be reported in the following tables. Samples MUST be reported if a statistical design is being captured (i.e. bio or tech replicates). If the type of replicates are not known, samples SHOULD NOT be reported.  species: The respective species of the samples analysed. For more complex cases, such as metagenomics, optional columns and userParams should be used.  tissue: The respective tissue(s) of the sample.  cell_type: The respective cell type(s) of the sample.  disease: The respective disease(s) of the sample.  description: A human readable description of the sample.  custom: Custom parameters describing the sample's additional properties. Dates MUST be provided in ISO-8601 format. 
    """ # noqa: E501
    id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    name: Optional[StrictStr] = Field(default=None, description="The sample's name.")
    custom: Optional[List[Parameter]] = Field(default=None, description="Additional user or cv parameters.")
    species: Optional[List[Parameter]] = Field(default=None, description="Biological species information on the sample.")
    tissue: Optional[List[Parameter]] = Field(default=None, description="Biological tissue information on the sample.")
    cell_type: Optional[List[Parameter]] = Field(default=None, description="Biological cell type information on the sample.")
    disease: Optional[List[Parameter]] = Field(default=None, description="Disease information on the sample.")
    description: Optional[StrictStr] = Field(default=None, description="A free form description of the sample.")
    __properties: ClassVar[List[str]] = ["id", "name", "custom", "species", "tissue", "cell_type", "disease", "description"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sample from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom (list)
        _items = []
        if self.custom:
            for _item in self.custom:
                if _item:
                    _items.append(_item.to_dict())
            _dict['custom'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in species (list)
        _items = []
        if self.species:
            for _item in self.species:
                if _item:
                    _items.append(_item.to_dict())
            _dict['species'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tissue (list)
        _items = []
        if self.tissue:
            for _item in self.tissue:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tissue'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cell_type (list)
        _items = []
        if self.cell_type:
            for _item in self.cell_type:
                if _item:
                    _items.append(_item.to_dict())
            _dict['cell_type'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in disease (list)
        _items = []
        if self.disease:
            for _item in self.disease:
                if _item:
                    _items.append(_item.to_dict())
            _dict['disease'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sample from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "custom": [Parameter.from_dict(_item) for _item in obj["custom"]] if obj.get("custom") is not None else None,
            "species": [Parameter.from_dict(_item) for _item in obj["species"]] if obj.get("species") is not None else None,
            "tissue": [Parameter.from_dict(_item) for _item in obj["tissue"]] if obj.get("tissue") is not None else None,
            "cell_type": [Parameter.from_dict(_item) for _item in obj["cell_type"]] if obj.get("cell_type") is not None else None,
            "disease": [Parameter.from_dict(_item) for _item in obj["disease"]] if obj.get("disease") is not None else None,
            "description": obj.get("description")
        })
        return _obj


