# coding: utf-8

"""
    mzTab-M reference implementation and validation API.

    This is the mzTab-M reference implementation and validation API service.

    The version of the OpenAPI document: 2.0.0
    Contact: nils.hoffmann@cebitec.uni-bielefeld.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from mztabm_client.models.comment import Comment
from mztabm_client.models.opt_column_mapping import OptColumnMapping
from mztabm_client.models.parameter import Parameter
from typing import Optional, Set
from typing_extensions import Self

class SmallMoleculeFeature(BaseModel):
    """
    The small molecule feature section is table-based, representing individual MS regions (generally considered to be the elution profile for all isotopomers formed from a single charge state of a molecule), that have been measured/quantified. However, for approaches that quantify individual isotopomers e.g. stable isotope labelling/flux studies, then each SMF row SHOULD represent a single isotopomer.  Different adducts or derivatives and different charge states of individual molecules should be reported as separate SMF rows.  The small molecule feature section MUST always come after the Small Molecule Table. All table columns MUST be Tab separated. There MUST NOT be any empty cells. Missing values MUST be reported using “null”.  The order of columns MUST follow the order specified below.  All columns are MANDATORY except for “opt_” columns. 
    """ # noqa: E501
    prefix: Optional[StrictStr] = Field(default='SMF', description="The small molecule feature table row prefix. SMF MUST be used for rows of the small molecule feature table.")
    header_prefix: Optional[StrictStr] = Field(default='SFH', description="The small molecule feature table header prefix. SFH MUST be used for the small molecule feature table header line (the column labels).")
    smf_id: StrictInt = Field(description="A within file unique identifier for the small molecule feature.")
    sme_id_refs: Optional[List[StrictInt]] = Field(default=None, description="References to the identification evidence (SME elements) via referencing SME_ID values. Multiple values MAY be provided as a “|” separated list to indicate ambiguity in the identification or to indicate that different types of data supported the identifiction (see SME_ID_REF_ambiguity_code). For the case of a consensus approach where multiple adduct forms are used to infer the SML ID, different features should just reference the same SME_ID value(s).")
    sme_id_ref_ambiguity_code: Optional[StrictInt] = Field(default=None, description="If multiple values are given under SME_ID_REFS, one of the following codes MUST be provided. 1=Ambiguous identification; 2=Only different evidence streams for the same molecule with no ambiguity; 3=Both ambiguous identification and multiple evidence streams. If there are no or one value under SME_ID_REFs, this MUST be reported as null.")
    adduct_ion: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The assumed classification of this molecule’s adduct ion after detection, following the general style in the 2013 IUPAC recommendations on terms relating to MS e.g. [M+H]1+, [M+Na]1+, [M+NH4]1+, [M-H]1-, [M+Cl]1-, [M+H]1+.")
    isotopomer: Optional[Parameter] = None
    exp_mass_to_charge: Union[StrictFloat, StrictInt] = Field(description="The experimental mass/charge value for the feature, by default assumed to be the mean across assays or a representative value. For approaches that report isotopomers as SMF rows, then the m/z of the isotopomer MUST be reported here.")
    charge: StrictInt = Field(description="The feature’s charge value using positive integers both for positive and negative polarity modes.")
    retention_time_in_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The apex of the feature on the retention time axis, in a Master or aggregate MS run. Retention time MUST be reported in seconds. Retention time values for individual MS runs (i.e. before alignment) MAY be reported as optional columns. Retention time SHOULD only be null in the case of direct infusion MS or other techniques where a retention time value is absent or unknown. Relative retention time or retention time index values MAY be reported as optional columns, and could be considered for inclusion in future versions of mzTab as appropriate.")
    retention_time_in_seconds_start: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The start time of the feature on the retention time axis, in a Master or aggregate MS run. Retention time MUST be reported in seconds. Retention time start and end SHOULD only be null in the case of direct infusion MS or other techniques where a retention time value is absent or unknown and MAY be reported in optional columns.")
    retention_time_in_seconds_end: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The end time of the feature on the retention time axis, in a Master or aggregate MS run. Retention time MUST be reported in seconds. Retention time start and end SHOULD only be null in the case of direct infusion MS or other techniques where a retention time value is absent or unknown and MAY be reported in optional columns..")
    abundance_assay: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="The feature’s abundance in every assay described in the metadata section MUST be reported. Null or zero values may be reported as appropriate.")
    opt: Optional[List[OptColumnMapping]] = Field(default=None, description="Additional columns can be added to the end of the small molecule feature table. These column headers MUST start with the prefix “opt_” followed by the {identifier} of the object they reference: assay, study variable, MS run or “global” (if the value relates to all replicates). Column names MUST only contain the following characters: ‘A’-‘Z’, ‘a’-‘z’, ‘0’-‘9’, ‘’, ‘-’, ‘[’, ‘]’, and ‘:’. CV parameter accessions MAY be used for optional columns following the format: opt{identifier}_cv_{accession}_\\{parameter name}. Spaces within the parameter’s name MUST be replaced by ‘_’. ")
    comment: Optional[List[Comment]] = None
    __properties: ClassVar[List[str]] = ["prefix", "header_prefix", "smf_id", "sme_id_refs", "sme_id_ref_ambiguity_code", "adduct_ion", "isotopomer", "exp_mass_to_charge", "charge", "retention_time_in_seconds", "retention_time_in_seconds_start", "retention_time_in_seconds_end", "abundance_assay", "opt", "comment"]

    @field_validator('prefix')
    def prefix_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SMF']):
            raise ValueError("must be one of enum values ('SMF')")
        return value

    @field_validator('header_prefix')
    def header_prefix_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SFH']):
            raise ValueError("must be one of enum values ('SFH')")
        return value

    @field_validator('adduct_ion')
    def adduct_ion_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\[\d*M([+-][\w]*)\]\d*[+-]$", value):
            raise ValueError(r"must validate the regular expression /^\[\d*M([+-][\w]*)\]\d*[+-]$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SmallMoleculeFeature from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "prefix",
            "header_prefix",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of isotopomer
        if self.isotopomer:
            _dict['isotopomer'] = self.isotopomer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in opt (list)
        _items = []
        if self.opt:
            for _item in self.opt:
                if _item:
                    _items.append(_item.to_dict())
            _dict['opt'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in comment (list)
        _items = []
        if self.comment:
            for _item in self.comment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['comment'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SmallMoleculeFeature from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prefix": obj.get("prefix") if obj.get("prefix") is not None else 'SMF',
            "header_prefix": obj.get("header_prefix") if obj.get("header_prefix") is not None else 'SFH',
            "smf_id": obj.get("smf_id"),
            "sme_id_refs": obj.get("sme_id_refs"),
            "sme_id_ref_ambiguity_code": obj.get("sme_id_ref_ambiguity_code"),
            "adduct_ion": obj.get("adduct_ion"),
            "isotopomer": Parameter.from_dict(obj["isotopomer"]) if obj.get("isotopomer") is not None else None,
            "exp_mass_to_charge": obj.get("exp_mass_to_charge"),
            "charge": obj.get("charge"),
            "retention_time_in_seconds": obj.get("retention_time_in_seconds"),
            "retention_time_in_seconds_start": obj.get("retention_time_in_seconds_start"),
            "retention_time_in_seconds_end": obj.get("retention_time_in_seconds_end"),
            "abundance_assay": obj.get("abundance_assay"),
            "opt": [OptColumnMapping.from_dict(_item) for _item in obj["opt"]] if obj.get("opt") is not None else None,
            "comment": [Comment.from_dict(_item) for _item in obj["comment"]] if obj.get("comment") is not None else None
        })
        return _obj


